apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: maximolds/bantay_data_webapp_client:v1
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: client-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80  # External port
      targetPort: 5173  # Container port for the client
  selector:
    component: web

